CREATE TABLE USERS (
  ID LONG PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE TICKETS(
  ID LONG PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255),
  STATUS VARCHAR(255) NOT NULL,
  FK_USER_ID LONG NOT NULL,

  CONSTRAINT FK_TICKETS_TO_USER FOREIGN KEY (FK_USER_ID) REFERENCES USERS (ID)
);


